[features]
seeds = false
skip-lint = false

[programs.localnet]
p2p_trade_facilitator_program = "FE7D2xK9qJQAYGDDXYTriLxv5f1TL5NEKyw9bVFnuZtt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/val/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
